services:
  postgres:
    container_name: postgres_db
    image: postgres:17.5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: tivon1234
    ports:
      - "5432:5432"
    networks:
      - app
    restart: unless-stopped
  
  academia:
    container_name: academia
    image: ghcr.io/arkatros/academianovit:latest
    depends_on:
      - postgres
    ports:
      - "8080:5000"
    restart: unless-stopped
    pull_policy: always
    networks:
      - app
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=AcademiaNovitDB;Username=admin;Password=tivon1234"

networks:
  app:
    driver: bridge