version: '3.8'
# Use postgres/example user/password credentials

services:

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - red-db
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - red-db
    restart: unless-stopped
    depends_on:
      - postgres


networks:
  red-db:
    driver: bridge
volumes:
    postgres:
    pgadmin: