global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'node_exporter'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          instance: 'cadvisor'

  - job_name: 'academia_app'
    static_configs:
      - targets: ['academia:5000']