# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: app.debugmail.io
        server_port: 25
        username: ${{ secrets.MAIL_ACCOUNT }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: GitHub Actions Mail Test
        to: jonatanm@dico.me
        from: john.doe@example.org
        content_type: text/html
        body: |
          <h1>Hola!</h1>
          <p>Este es un mail de prueba desde GitHub Actions con DebugMail.</p>
