name: GH-docker-deploy-dev

on:
  push:
    branches: [ "main" ]
jobs:

  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag academianovit:latest
    - name: Login Registry
      run: docker login ghcr.io -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.ACCESS_TOKEN }}
    - name: Re-Tag
      run: docker build . --file Dockerfile --tag ghcr.io/arkatros/academianovit:latest
    - name: Upload image to Registry
      run: docker push ghcr.io/arkatros/academianovit:latest  
    - name: Run docker-compose to PROD
      uses: appleboy/ssh-action@v1
      with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker compose -f "docker-ubuntu.yml" up -d

      
