name: ComandoSSH
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            if [ -d "AcademiaNovit2025" ]; then
              cd AcademiaNovit2025
              git fetch
              git pull
            else
              git clone https://github.com/Arkatros/AcademiaNovit2025
              cd AcademiaNovit2025
            fi

            ls -al
